module.exports={
    voltage:{
        value:0,
        des:'电压',
        update:''
    },
    current:{
        value:0,
        des:'电流',
        update:''
    },
    speed:{
        value:0,
        des:'速度',
        update:''
    },
    value1:{
        value:0,
        des:'数值1',
        update:''
    },    
    value2:{
        value:0,
        des:'数值2',
        update:''
    },
    value3:{
        value:0,
        des:'数值3',
        update:''
    },
    value4:{
        value:0,
        des:'数值4',
        update:''
    },
    value5:{
        value:0,
        des:'数值5',
        update:''
    }
}